### ISSUE TITLE
projectile integration?

### ISSUE THREAD

**Issue by edrex** [syohex/emacs-helm-github-issues#1]
It would be awesome if this package could try to discover the upstream repo for the current projectile, so that it would work without configuration.

**Comment by syohex** [comment]
Please check https://github.com/syohex/emacs-helm-open-github.  You can use `helm-open-github-from-issues` command for your purpose. And it supports pull request and has some other features.

**Comment by edrex** [comment]
Thanks, I'll try it! Does that package package replace this one, or are you going to keep supporting both?

**Comment by syohex** [comment]
> Does that package replace this one

Yes
